---
# installing apache 
- hosts: all
  become: yes
  tasks:
    - name: installing apache on ubuntu servers
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      notify: 
        - restart apache
    - name: installing apache on redhat
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"
      notify: 
        - restart apache
  handlers:
    - name: restart apache
      service: 
        name: apache2
        state: restarted
      when: ansible_os_family == "Debian"
    - name: restart apache
      service:
        name: httpd
        state: restarted
      when: ansible_os_family == "RedHat"