---
# installing tomcat9 using variables
- hosts: all
  become: yes
  tasks:
    - name: uninstalling tomcat on Ubuntu
      apt:
        name: "{{ packagename }}"
        state: absent
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: uninstalling tomcat on ubuntu
      yum:
        name: "{{ packagename }}"
        state: absent
      when: ansible_os_family == "redHat"  
