---
# installing tomcat9 using variables
- hosts: all
  become: yes
  tasks:
    - name: installing tomcat on Ubuntu
      apt:
        name: "{{ packagename }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: installing tomcat on ubuntu
      yum:
        name: "{{ packagename }}"
        state: present
      when: ansible_os_family == "redHat"  
