---
# tasks file for php
  - name: install packages
    apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes 
    with_items: ["git","mcrypt","nginx"]
  - name: installing php7
    apt:
      name: php7
      state: present
      update_cache: yes  
