---
# tasks file for php
  - name: install packages on Ubuntu
    apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes 
    when: ansible_os_family == "Debian"
    with_items: ["git","mcrypt","nginx"]
  - name: install packages on RedHat
    yum: 
      name: ["git","mcrypt","nginx","epel-release","yum-utils"]
      state: present
      update_cache: yes 
    when: ansible_os_family == "RedHat"
       
  - name: installing php on Ubuntu
    apt:
      name: php
      state: present
      update_cache: yes 
    when: ansible_os_family == "Debian"
  - name: installing php on RedHat
    yum:
      name: php72
      state: present
      update_cache: yes 
    when: ansible_os_family == "RedHat"