---
# tasks file for php
  - name: install packages
    apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes 
    with_items: ["git","mcrypt","nginx"]
  - name: installing php7
    apt:
      name: php7
      state: present
      update_cache: yes  
  - name: enable php5 mcrypt module
    shell: php5enmod mcrypt
    args:
      creates: /etc/php5/cli/conf.d/20-mcrypt.ini